services:
  opensearch:
    build:
      context: ./opensearch
    volumes:
      - ./opensearch:/app/opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - plugins.security.ssl.http.enabled=true
      - DISABLE_INSTALL_DEMO_CONFIG=false  # デモ設定の自動インストールを有効化
      - DISABLE_SECURITY_PLUGIN=false      # セキュリティプラグインを有効化
      # - plugins.security.ssl.http.pemcert_filepath=/usr/share/opensearch/config/cert.pem
      # - plugins.security.ssl.http.pemkey_filepath=/usr/share/opensearch/config/key.pem
    ports:
      - 9200:9200
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: "https://opensearch:9200"
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    networks:
      - opensearch-net

  web:
    build:
      context: ./web
    volumes:
      - ./web:/app/web
    ports:
      - "8000:8000"
    command: uv run manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    depends_on:
      - db
      - opensearch
    networks:
      - opensearch-net

  db:
    image: postgres:17.4
    ports:
        - "5432"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - opensearch-net

networks:
  opensearch-net:
    driver: bridge
